zookeeper:
    image: bitnami/zookeeper 
    ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
mesosmaster:
    image: mesosphere/mesos-master:1.6.2
    ports:
        - "5050:5050"
    links:
        - zookeeper:zk
    environment:
        - MESOS_ZK=zk://zk:2181/mesos
        - MESOS_LOG_DIR=/var/log/mesos
        - MESOS_QUORUM=1
        - MESOS_REGISTRY=in_memory
        - MESOS_WORK_DIR=/var/lib/mesos
marathon:
    image: mesosphere/marathon
    links:
        - zookeeper:zk
        - mesosmaster:master
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon
    ports:
        - "8080:8080"
mesosslave:
    image: mesosphere/mesos-slave:1.6.2
    ports:
        - "5051:5051"
    links:
        - zookeeper:zk
        - mesosmaster:master
    entrypoint: mesos-slave
    environment:
        - MESOS_HOSTNAME=192.168.33.10
        - MESOS_ZK=zk://zk:2181/mesos
        - MESOS_LOG_DIR=/var/log/mesos
        - MESOS_LOGGING_LEVEL=INFO
