wordpress:
    image: wordpress
    links:
        - mysql
    ports:
        - "80:80"
    environment:
        - WORDPRESS_DB_NAME=wordpress
        - WORDPRESS_DB_USER=wordpress
        - WORDPRESS_DB_PASSWORD=wordpress
mysql:
    image: mysql
    volumes:
        - /home/docker/mysql:/var/lib/mysql
    environment:
        - MYSQLROOT_ROOT_PASSWORD=wordpressdocker
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpresspwd
