# -*- mode: ruby -*-
# vi: set ft=ruby :
$bootstrap=<<-SCRIPT
apt-get update
apt-get install -y wget
wget -qO- https://get.docker.com | sh
usermod -aG docker vagrant
service docker restart
apt install -y python-pip
pip install -U pip
pip install -U docker-compose
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: $bootstrap

end
