# -*- mode: ruby -*-
# vi: set ft=ruby :
$bootstrap_master=<<-SCRIPT
apt-get update
apt-get install -y wget curl apt-transport-https
wget -qO- https://get.docker.com | sh
usermod -aG docker vagrant
service docker restart
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
apt-get update
apt-get install -y kubectl
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
cp minikube /usr/local/bin && rm minikube
minikube start --vm-driver=none
SCRIPT

$bootstrap_node=<<-SCRIPT
apt-get update
apt-get install -y wget curl apt-transport-https
wget -qO- https://get.docker.com | sh
usermod -aG docker vagrant
service docker restart
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
apt-get update
apt-get install -y kubectl
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "debian/stretch64"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    master.vm.provision "shell", inline: $bootstrap_master
  end

  config.vm.define "node" do |node|
    node.vm.box = "debian/stretch64"
    node.vm.network "private_network", ip: "192.168.33.10"
    node.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    node.vm.provision "shell", inline: $bootstrap_node
  end

end
