apiVersion: v1
kind: ReplicaSet
metadata:
    labels:
        name: rcgame
    name: rcgame
spec:
    replicas: 1
    selector:
        name: game
    template:
        metadata:
            labels:
                name: game
        spec:
            containers:
            - image: cpk1224/docker-2048
              name: test
              ports:
              - containerPort: 80
                hostPort: 80
