# -*- mode: ruby -*-
$bootstrap_docker=<<-SCRIPT
apt-get update
apt-get install -y wget
wget -qO- https://get.docker.com | sh
usermod -aG docker vagrant
service docker restart
SCRIPT

Vagrant.configure(2) do |config|

 config.vm.define "master" do |master|
   master.vm.box ="debian/stretch64"
   master.vm.network "private_network", ip: "192.168.200.10"
   master.vm.hostname = "master"
   master.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
   end
   master.vm.provision "shell", inline: $bootstrap_docker
 end

 config.vm.define "node" do |node|
   node.vm.box ="debian/stretch64"
   node.vm.network "private_network", ip: "192.168.200.11"
   node.vm.hostname = "node"
   node.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
   end
   node.vm.provision "shell", inline: $bootstrap_docker
 end

end
