# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$bootstrap=<<SCRIPT
apt-get update
apt-get -y install curl
apt-get -y install bridge-utils
curl -sSL https://get.docker.com | sh
usermod -aG docker vagrant
service docker restart
curl -L git.io/weave -o /usr/local/bin/weave
chmod a+x /usr/local/bin/weave
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  num_nodes = 2
  base_ip = "172.18.8."
  net_ips = num_nodes.times.collect { |n| base_ip + "#{n+101}" }

  num_nodes.times do |n|
    config.vm.define "weave0#{n+1}" do |net|
      net.vm.box = "debian/stretch64"
      net_ip = net_ips[n]
      net_index = n+1
      net.vm.hostname = "weave0#{net_index}"
      net.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
      net.vm.network :private_network, ip: "#{net_ip}"
      net.vm.provision :shell, inline: $bootstrap
    end
  end

end
